// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNC0ZiVSUa36WJebr893PUJVSFVIQZZx4',
    appId: '1:114761352546:web:ba6207980eb061e57a983b',
    messagingSenderId: '114761352546',
    projectId: 'flutterlinuxebook',
    authDomain: 'flutterlinuxebook.firebaseapp.com',
    databaseURL: 'https://flutterlinuxebook-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlinuxebook.firebasestorage.app',
    measurementId: 'G-YPTSXV4GZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlUdmg_HCOOL8CibNSXTE7CigzX6L74Gw',
    appId: '1:114761352546:android:a8e33156967e0fdf7a983b',
    messagingSenderId: '114761352546',
    projectId: 'flutterlinuxebook',
    databaseURL: 'https://flutterlinuxebook-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlinuxebook.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdBzQWICCBb8xh9J3C50SKll6s7clZLuw',
    appId: '1:114761352546:ios:b8a95942363c92557a983b',
    messagingSenderId: '114761352546',
    projectId: 'flutterlinuxebook',
    databaseURL: 'https://flutterlinuxebook-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlinuxebook.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdBzQWICCBb8xh9J3C50SKll6s7clZLuw',
    appId: '1:114761352546:ios:b8a95942363c92557a983b',
    messagingSenderId: '114761352546',
    projectId: 'flutterlinuxebook',
    databaseURL: 'https://flutterlinuxebook-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlinuxebook.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNC0ZiVSUa36WJebr893PUJVSFVIQZZx4',
    appId: '1:114761352546:web:ddf96abec166e3107a983b',
    messagingSenderId: '114761352546',
    projectId: 'flutterlinuxebook',
    authDomain: 'flutterlinuxebook.firebaseapp.com',
    databaseURL: 'https://flutterlinuxebook-default-rtdb.firebaseio.com',
    storageBucket: 'flutterlinuxebook.firebasestorage.app',
    measurementId: 'G-N59BY22WCN',
  );
}
