// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6CK8wyeIz7tEiCU1hKwr1an_B5CIAofU',
    appId: '1:957800962175:web:14e95bfdc99ad30fef074a',
    messagingSenderId: '957800962175',
    projectId: 'admin-61c36',
    authDomain: 'admin-61c36.firebaseapp.com',
    storageBucket: 'admin-61c36.firebasestorage.app',
    measurementId: 'G-ZE6RHGKSHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFz7WORq78db54vqKVSKu_xXcCVcjGl3M',
    appId: '1:957800962175:android:558be3fe1191e73fef074a',
    messagingSenderId: '957800962175',
    projectId: 'admin-61c36',
    storageBucket: 'admin-61c36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9mIAcImsE9oB9YjJzdSWQ6rtKtw8NE_o',
    appId: '1:957800962175:ios:660c8f2f30b6ed12ef074a',
    messagingSenderId: '957800962175',
    projectId: 'admin-61c36',
    storageBucket: 'admin-61c36.firebasestorage.app',
    iosBundleId: 'com.example.flutterEbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9mIAcImsE9oB9YjJzdSWQ6rtKtw8NE_o',
    appId: '1:957800962175:ios:660c8f2f30b6ed12ef074a',
    messagingSenderId: '957800962175',
    projectId: 'admin-61c36',
    storageBucket: 'admin-61c36.firebasestorage.app',
    iosBundleId: 'com.example.flutterEbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6CK8wyeIz7tEiCU1hKwr1an_B5CIAofU',
    appId: '1:957800962175:web:fc0a904d238cc12fef074a',
    messagingSenderId: '957800962175',
    projectId: 'admin-61c36',
    authDomain: 'admin-61c36.firebaseapp.com',
    storageBucket: 'admin-61c36.firebasestorage.app',
    measurementId: 'G-K9DNZ54ET1',
  );
}
